### ISSUE TITLE
Custom job infrastructure checklist

### ISSUE THREAD

**Issue by cofiem** [QutBioacoustics/baw-server#188]
Currently the website has backend support for jobs, datasets, and scripts, however none of this is used or displayed in the UI.

The proposal is to simplify the original plan to use serialised filter queries rather than datasets, and provide only an API. The UI will be built in baw-client.

For this to happen, and few things need to be checked and changed. The following is a list of issues that need to be created/discussed:

 - [x] Remove dataset model
 - [x] Check that Scripts does what is needed (e.g. command line template, settings template, identifier)
 - [x] The job model needs to change to be able to store a filter query.
 - [x] There needs to be some way to retrieve the resque jobs that relate to a custom job to determine progress and status. We don't want to store the resque job ids, so this will require some way to filter the resque jobs using the custom job id.
 - [x] An API is needed for CR_D actions. Custom jobs can be created; their description, analysis settings, progress, and status can be queried; they can be re-run, and they can be deleted. To modify a custom job, it must be cloned, modified, then run as a new custom job.

**Comment by atruskie** [comment]
Good points, I'll break these down into issues tomorrow.

Need to clarify some detail from @jwim1 's spec first

**Comment by atruskie** [comment]
Closing in favour of milestone.

See #189, #190, #191, #192, #193,
