### ISSUE TITLE
Tracking issue for implementing custom jobs

### ISSUE THREAD

**Issue by cofiem** [QutBioacoustics/baw-server#200]
## Step 1

Establish requirements for models and APIs
 - [x] datasets #189
 - [x] scripts #190 
 - [x] jobs #191 #195  
 - [x] saved_searches #199 #194 #64
 - [x] how to obtain and store permissions from filter (using project references). Current options: `(custom_)jobs_projects` table, `projects_saved_searches` table. #199 #195

## Step 2 

 - [x] Remove datasets model and APIs
 - [x] implement saved_searches model and APIs
 - [x] modify jobs model and APIs

Excludes API for job results.

## Step 3

 - [x] Create way to generate resque jobs from custom jobs and saved_searches #198 
 - [x] Create API for job results #196

## Step 4

 - [ ] Create way to get resque jobs for one custom job id #192
 - [ ] Ensure saved search API works #194

## Step 5

 - [ ] Ensure custom job workflow is viable #193
 - [ ] Ensure permission to custom jobs API is set up correctly #195

**Comment by atruskie** [comment]
This seems like a good plan of attack.
